-- MySQL Script generated by MySQL Workbench
-- Sun Feb 10 19:15:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema UserDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema UserDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UserDB` ;
USE `UserDB` ;

-- -----------------------------------------------------
-- Table `UserDB`.`StudentDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserDB`.`StudentDetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `registrationId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` TEXT NOT NULL,
  `dateOfBirth` DATETIME NOT NULL,
  `contactNumber` INT NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  `section` VARCHAR(45) NOT NULL,
  `parentName` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NOT NULL,
  `classTeacher` VARCHAR(45) NOT NULL,
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserDB`.`TeacherDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserDB`.`TeacherDetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `registrationId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` TEXT NOT NULL,
  `dateOfBirth` DATETIME NOT NULL,
  `contactNumber` INT NOT NULL,
  `designation` VARCHAR(45) NULL,
  `qualification` VARCHAR(45) NULL,
  `specialisedSubject` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NOT NULL,
  `class` VARCHAR(45) NULL,
  `type` INT NOT NULL,
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` INT NOT NULL DEFAULT 0,
  `TeacherDetailscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserDB`.`UserCredentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserDB`.`UserCredentials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `registrationId` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
