-- MySQL Script generated by MySQL Workbench
-- Tue Jul 14 00:19:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema UserDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema UserDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UserDB` ;
-- -----------------------------------------------------
-- Schema Twitter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Twitter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Twitter` DEFAULT CHARACTER SET ucs2 COLLATE ucs2_general_mysql500_ci ;
USE `UserDB` ;

-- -----------------------------------------------------
-- Table `UserDB`.`StudentDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserDB`.`StudentDetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `registrationId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` TEXT NOT NULL,
  `dateOfBirth` DATETIME NOT NULL,
  `contactNumber` INT NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  `section` VARCHAR(45) NOT NULL,
  `parentName` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NOT NULL,
  `classTeacher` VARCHAR(45) NOT NULL,
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserDB`.`TeacherDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserDB`.`TeacherDetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `registrationId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` TEXT NOT NULL,
  `dateOfBirth` DATETIME NOT NULL,
  `contactNumber` INT NOT NULL,
  `designation` VARCHAR(45) NULL,
  `qualification` VARCHAR(45) NULL,
  `specialisedSubject` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NOT NULL,
  `class` VARCHAR(45) NULL,
  `type` INT NOT NULL,
  `createdOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` INT NOT NULL DEFAULT 0,
  `TeacherDetailscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserDB`.`UserCredentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserDB`.`UserCredentials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `registrationId` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `Twitter` ;

-- -----------------------------------------------------
-- Table `Twitter`.`followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Twitter`.`followers` (
  `parentUserId` INT NOT NULL,
  `childUserId` INT NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`parentUserId`, `childUserId`),
  INDEX `idx_parentuserid` (`parentUserId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Twitter`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Twitter`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(180) NULL,
  `createdOn` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deletedOn` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Twitter`.`tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Twitter`.`tweet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `msg` BLOB NULL,
  `deletedOn` TINYINT(1) NULL DEFAULT 0,
  `createdOn` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOn` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
